### ISSUE TITLE
Error while loading hrnet32_idih256 model

### ISSUE THREAD

**Issue by mShuvi** [saic-vul/image_harmonization#1]
Hey,

When I try to load this model: hrnet32_idih256.pth, I encounter this error
RuntimeError: storage has wrong size: expected 0 got 256.
There's any chance this model wasn't saved properly?

Thank you~

**Comment by ksofiyuk** [comment]
Hi,
I couldn't reproduce your issue. I downloaded `hrnet32_idih256.pth` and checked it with a command:
```.bash
python3 scripts/evaluate_model.py hrnet32_idih256 weights/hrnet32_idih256.pth --resize-strategy Fixed256
```
Do you have the same problem with other models?

**Comment by mShuvi** [comment]
It seems like you updated [backboned.py](https://github.com/saic-vul/image_harmonization/blob/master/iharm/mconfigs/backboned.py) file and now it works :)
Thanks!
