### ISSUE TITLE
How to compute MSE in each foreground ratio range?

### ISSUE THREAD

**Issue by zhangboshen** [saic-vul/image_harmonization#3]
Hi, congregation，this is a great work!

Here I have a question about how to compute MSE (fMSE) in different foreground ratio range (0%-5%, 5%-15%, etc)
, just like in your paper?

**Comment by polyhex-sqr** [comment]
Hi there,
Sorry for such a late answer, hope it helps.

There's a [script](https://github.com/saic-vul/image_harmonization/blob/master/scripts/evaluate_model_fg_ratios.py) for this kind of evaluation. You can run the following:
`python3 scripts/evaluate_model_fg_ratios.py improved_dih256 /hdd0/harmonization_exps/fixed256/improved_dih/checkpoints/last_checkpoint.pth --resize-strategy Fixed256`
