### ISSUE TITLE
How to resume model training?

### ISSUE THREAD

**Issue by EricStarer** [saic-vul/image_harmonization#4]
how to use parameter resume-exp and resume-prefix, could you give an example?

**Comment by polyhex-sqr** [comment]
Here's a short description of these arguments:
`resume-exp` -- name prefix of the experiment you would like to resume
`resume-prefix` -- name prefix of the checkpoint stored in the corresponding experiment directory with which the model weights should initialized

Let's say you want to resume your experiment `fixed256/improved_dih/001_some_name` starting from epoch 8. Check that the corresponding checkpoint `008.pth` is saved at `fixed256/improved_dih/001_some_name/checkpoints`. Then run the following command to resume your model training:
`python train.py models/fixed256/improved_dih.py --gpus=0,1 --workers=1 --resume-exp=001 --resume-prefix 008 --start-epoch 8`

**Comment by EricStarer** [comment]
got it , I'll have a try. thanks a lot
