### ISSUE TITLE
How to reproduce the results in the WACV paper?

### ISSUE THREAD

**Issue by weixiong-ur** [saic-vul/image_harmonization#9]
Hi,
I wonder what config can lead to the results present in the WACV paper, i.e., MSE=22, fMSE=252, PSNR=38.31. 

Best,

**Comment by polyhex-sqr** [comment]
Hi @weixiong-ur

Unfortunately, we refactored our code before publishing the weights, and all the models were retrained from scratch. So, metric values may differ slightly from the ones in the paper.
